### ISSUE TITLE
stealing from locked chests with hopper carts

### ISSUE THREAD

**Issue by Castiella** [megoesrawr/Modern-LWC#100]
Using most recent dev build - 

People can steal from locked chests by simply placing a hopper cart underneath. All of the items then flow into the hopper cart. Is there a fix for this please?

**Comment by megoesrawr** [comment]
https://i.imgur.com/0o0oCLQ.png Unable to replicate. It might be another plugin messing with it.

**Comment by SimonOrJ** [comment]
This seems to be a PEBKAC rather than a bug.  Did you use `/chopper on` or `/chopper off` on the chest?
