### ISSUE TITLE
Request: opposite of /cdonation - /cobtain?

### ISSUE THREAD

**Issue by sawarahh** [megoesrawr/Modern-LWC#101]
**LWC Version (/lwc admin version):** 
2.0.7
**Server version (/version):** 
1.12.2 (but will be switching to 1.13 as soon as it's available)
**Short five word summary of issue:** 
Public donation center - sorted chests

**Detailed description of problem:**
Players donate items in a donate chest that then goes through a sorter. 
We have a need for output chests, where players can come and take what they want from a sorted chest, without placing items in said chest and disorganizing the sorting.

**If there was an error in console, put it here:**
```
N/A
```

**Comment by Tsuser1** [comment]
Well I was just trying to add the enhancement tag for now, but thanks GitHub!

**Comment by sawarahh** [comment]
Thanks for being so proactive and working on this immediately @Tsuser1! Lol.

**Comment by Tsuser1** [comment]
Upon further review my team has marked this issue as *invalid*. Feel free to join the discord on [our new repository](https://github.com/Tsuser1/Modern-LWC) if you wish to discuss this. Thanks!

**Issue closed.**
