### ISSUE TITLE
problem with commands

### ISSUE THREAD

**Issue by Raphy123** [megoesrawr/Modern-LWC#104]
When I want to remove a protection

[12:07:36 INFO]: Raphy123 issued server command: /cremove
[12:07:36 INFO]: [LWC] onDestroyProtection

I have the message : "click on the protect..."

But the chest don't remove the lock. 
same for cmodify

**Comment by megoesrawr** [comment]
Works fine for me. Try the snapshot from Jenkins.

**Comment by Tsuser1** [comment]
Unreproducible.

**Issue closed.**
