### ISSUE TITLE
LWC Steal Bug With Orebfuscator

### ISSUE THREAD

**Issue by Ant4rez** [megoesrawr/Modern-LWC#106]
**LWC Version (/lwc admin version):** 
1.9.4
**Server version (/version):** 
CraftBukkit version git-Spigot-eb3d921-b9f1615 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
**Short five word summary of issue:** 
LWC Steal Bug With Orebfuscator
**Detailed description of problem:**
When a player quickly approaches a block transformed into stone, such as chests, furnaces, etc. Due to the orebfuscator plugin, you have the possibility to open them, even though they are protected, and therefore can steal your content, your items, etc.

I have attached a video as evidence:
[Evidence.zip](https://github.com/megoesrawr/Modern-LWC/files/2212741/Evidence.zip)
The video is in Spanish, but the problem is clearly understood at the moment of viewing it.
Also i take this opportunity to leave my list of plugins, if it's any good:
https://hastebin.com/alirunavot.nginx

Regards.

**Comment by megoesrawr** [comment]
Try this - http://jenkins.theemeraldage.com:8080/job/Modern%20LWC/47/

**Comment by Ant4rez** [comment]
Also doesn't work. The player, disconnected, then moved away, and approached the chest, which was transformed into stone, and again could open it.

**Comment by megoesrawr** [comment]
Try this: http://jenkins.theemeraldage.com:8080/job/Modern%20LWC/49/

**Comment by megoesrawr** [comment]
[2018-07-21 18-36-00.zip](https://github.com/megoesrawr/Modern-LWC/files/2216566/2018-07-21.18-36-00.zip)

**Comment by Ant4rez** [comment]
Now the chests doesn't open, you can't see the gui also for furnaces.

**Comment by megoesrawr** [comment]
Try #50 or the newest one http://jenkins.theemeraldage.com:8080/job/Modern%20LWC/50/

**Comment by Tsuser1** [comment]
Problem is not with Moden LWC.

**Issue closed.**
