### ISSUE TITLE
Door break then protect a double door

### ISSUE THREAD

**Issue by ChrisWeymann** [megoesrawr/Modern-LWC#108]
**LWC Version (/lwc admin version):** 
2.0.7

**Server version (/version):** 
Spigot git rev a85f7ec (MC 1.13)

**Short five word summary of issue:** 
Door break then protect a double door

**Detailed description of problem:**
Then you protect a double door then the second door will be destroyed.

You can see it in this video ( https://youtu.be/73DS0Fu2oGE )

**If there was an error in console, put it here:**
```
22:51:19[LWC] onBlockInteract com.griefcraft.scripting.event.LWCBlockInteractEvent@5d24fa4f
```

**Comment by megoesrawr** [comment]
1.13 is not supported yet. There was a LOT of changes between the 1.12 and 1.13. Sorry.

**Comment by ChrisWeymann** [comment]
ah ok thanks for the respnse. We have now disable the door protect until an update is available.

**Comment by Tsuser1** [comment]
Hey, can you try our latest Jenkins build #54?
