### ISSUE TITLE
Single chests next to each other are still considered double chest

### ISSUE THREAD

**Issue by SimonOrJ** [megoesrawr/Modern-LWC#109]
**LWC Version (/lwc admin version):** 2.0.8-snapshot  (Jenkins #\50)
**Server version (/version):** Spigot 1.13 (CraftBukkit version git-Spigot-69774b3-8592585)

**Short five word summary of issue:** Close chests are not double

**Detailed description of problem:**
In 1.13, not all chests that are placed next to each other are double chests, but LWC treats them as if they're double chests.  This makes locking/unlocking not work properly.

I suggest LWC to use DoubleChest class to check for double chests.

**If there was an error in console, put it here:**
```
[23:37:01 INFO]: [LWC] Removing corrupted protection: Private CHEST§f §2Id=1481 Owner=39d83509-f85f-492a-ba8d-f54ad74c2682 Location=[world 249,67,283] Created=2018-07-30 23:36:51.958 Flags= LastAccessed=10 seconds ago
```

**Comment by Tsuser1** [comment]
So, the problem here is 1.13 changed how double chests are formed. Our code validates using the old method, so basically we need to make a new way of checking for double chests.
