### ISSUE TITLE
Some (random?) chests do not unlock (until reload)

### ISSUE THREAD

**Issue by SimonOrJ** [megoesrawr/Modern-LWC#110]
**LWC Version (/lwc admin version):** 2.0.8-snapshot (Jenkins #\50)
**Server version (/version):** Spigot 1.13 (CraftBukkit version git-Spigot-69774b3-8592585)

**Short five word summary of issue:** Double Chests do not unlock

**Detailed description of problem:**

When unlocking some double chests or double-chest-turned-single, it will show the "chest unlocked" message but the chest won't actually unlock.  Pre-existing locked chest are not affected.

Reloading LWC will show that chest is unlocked.

Might be related to #109

**If there was an error in console, put it here:**
```
[23:44:17 INFO]: [LWC] onDestroyProtection
```

**Comment by megoesrawr** [comment]
1.13 is not really supported yet.

**Comment by SimonOrJ** [comment]
Of #107, I suppose?
Title of issue was confusing so I missed it
