### ISSUE TITLE
Inventory GUI does not load until you invoke LWC-locked block

### ISSUE THREAD

**Issue by SimonOrJ** [megoesrawr/Modern-LWC#111]
**LWC Version (/lwc admin version):** 2.0.8-snapshot (Jenkins #\50)
**Server version (/version):** Spigot 1.13 (CraftBukkit version git-Spigot-69774b3-549d9b0)

**Short five word summary of issue:** Inventory GUI not loading randomly

**Detailed description of problem:**

At random, inventory GUI (Chest, Crafting Table, Enchanting Table, Furnace, etc.) does not load when opening block with GUI.  When you open or try to open an LWC-locked inventory and then try it again, then it starts working again.

There are no errors logged on console.

Edit: This is most likely related to #109 as corrupted chest error came before GUI stopped working

Edit 2: This might have something to do with ProtocolLib

**Comment by megoesrawr** [comment]
Im not getting this problem on my server. Can I get some video or something?

**Comment by SimonOrJ** [comment]
My server no longer uses LWC since its 1.13 support isn't complete yet, but it did used to happen randomly.

I don't have reproduction steps because the issue seemingly occured at random while many players were playing on the server doing their own thing at the same time. It's hard to pinpoint the exact cause of this.

I'm sure the issue comes from LWC because all right click action becomes unavailable for everyone until someone attempts to interact with an LWC-protected container.

**Comment by Tsuser1** [comment]
Fixed by removing the ProtocolLib stuff we added trying to fix misc. other issues which just caused more.

**Issue closed.**
