### ISSUE TITLE
#973 - Open any lock with Flint&Steel

### ISSUE THREAD

**Issue by Dragoboss** [megoesrawr/Modern-LWC#116]
**LWC Version (/lwc admin version):** 2.0.7
**Server version (/version):** 1.12.2 Paper-Spigot #1487

**Short five word summary of issue:**
Open any lock with flint&steel

**Detailed description of problem:**
Repost of bug  #973 of original LWC github repo.
Updated with actual proof (video).
Whenever someone tries to open a chest/hopper/locked-entity whilst holding a flint&steel they get free access to the entity, even while chat will say 'locked with magical spell'
Please refer to video: https://www.twitch.tv/videos/294515153

**If there was an error in console, put it here:**
``` no errors present ```

**Comment by megoesrawr** [comment]
I think this is a bug with another one of your plugins, NOT LWC. I've tried this so many times and I cant get this to work.

**Comment by Tsuser1** [comment]
**Not reproducible,** please check your plugins.

**Issue closed and locked.**
