### ISSUE TITLE
Certain mobs wont spawn

### ISSUE THREAD

**Issue by riley00** [megoesrawr/Modern-LWC#117]
**LWC Version (/lwc admin version):** 2.0.8
**Server version (/version):** Paper 106

**Short five word summary of issue:**  Certain mobs aren't spawning.

**Detailed description of problem:**
Certain mobs won't spawn in the world naturally, via eggs or spawners. LWC outputs "Player spawned entity skeleton" and "null" in console

**If there was an error in console, put it here:**
 LWC outputs "Player spawned entity skeleton" and "null" in console

```
09.08 11:26:16 [Server] INFO [LWC] Player created entity [SKELETON]
09.08 11:26:16 [Server] INFO [LWC] null
```

**Comment by megoesrawr** [comment]
Which mobs aren't spawning?

**Comment by Tsuser1** [comment]
Doesn't seem to be an issue in the latest build, cannot reproduce. Try the latest builds.

**Issue closed.**
