### ISSUE TITLE
Error when placing paintings, spawning mobs, etc

### ISSUE THREAD

**Issue by aeonlamb** [megoesrawr/Modern-LWC#119]
**LWC Version (/lwc admin version):** 2.0.8
**Server version (/version):** Spigot-417cfb3-a0a27e5 (spigot 1.13)

Whenever you place paintings, item frames, armor stands, or spawn any mobs (using spawn eggs), an error will get printed to the console. It does not matter if the entity is allowed to be locked in the config file or not, it just applies to seemingly any entity. 

Oddly, minecarts and boats do not seem to be affected by this bug.

**Errors:**
```
[18:16:40] [Server thread/INFO]: [LWC] Player created entity [ARMOR_STAND]
[18:16:40] [Server thread/INFO]: [LWC] null
```

**Comment by Tsuser1** [comment]
Fixed by "fix a NPE" commit.

**Issue closed.**
