### ISSUE TITLE
/lock isn't working

### ISSUE THREAD

**Issue by DeveloperBoy** [megoesrawr/Modern-LWC#123]
**LWC Version (/lwc admin version):** 
2.1.0-dev-43ab4f6
**Server version (/version):** 
Spigot 1.10.2 with ViaVersion (latest)
**Short five word summary of issue:** 
/lock isn't working?

**Detailed description of problem:**
When I run the command /lock and then left click on a block, it doesn't add the lock. I have tried it on a iron door, but it doesn't work?

**If there was an error in console, put it here:**
```
No error
```

**Comment by pop4959** [comment]
LWC 2.1.0-dev-43ab4f6 is exclusively for servers running on MineCraft 1.13. Please use a previous version instead (such as 1.9.4) which can be found on the Spigot resource page, under "Version History".
