### ISSUE TITLE
Server hangs on shutdown at "flushing protection updates"

### ISSUE THREAD

**Issue by SFTMedia** [megoesrawr/Modern-LWC#124]
**LWC Version (/lwc admin version):** 
2.1.3-dev-c1d515f/

**Server version (/version):** 
git-Spigot-f09662d-3697519 (MC: 1.13.2) 

**Short five word summary of issue:** 
Server hangs at "flushing protection updates" on shutdown

**Detailed description of problem:**
The server hangs at "flushing protection updates" on shutdown if it hasn't been restarted for 2+ days (some times even less).
In order to recover, I have to kill the java process.
NOTE:  I am running MariaDB and the SQL server has no issues (I use it for a lot of other things so I would know if it was an issue)

**Comment by pop4959** [comment]
@SFTMedia This repository is dead. Please post the issue at https://github.com/Tsuser1/Modern-LWC/issues.

@Tsuser1 can you close this one
