### ISSUE TITLE
Armorstand protection double messages

### ISSUE THREAD

**Issue by Sikatsu** [megoesrawr/Modern-LWC#74]
It seems if I want to put something in the armorstands hand, it throws the protection message twice.

**Comment by megoesrawr** [comment]
This is because there is 2 events that happen when you put something in an armorstands hand or w/e. I cant remove them because they are both needed. I will see if I can do something, but this is kinda minor.

**Comment by megoesrawr** [comment]
Yes, Thanks for the report though.

**Comment by Tsuser1** [comment]
Additional information in #81.

**Comment by theyapps** [comment]
Can anyone confirm does this happen one 2.0.7

**Comment by Sikatsu** [comment]
This still happens on 2.0.7. As soon as I give the armorstand hands and want to put something in his hand it triggers twice.

**Comment by Tsuser1** [comment]
Caused by another plugin, related to buggy unsupported entity protections.

**Issue closed.**
