### ISSUE TITLE
Menu mode not implemented

### ISSUE THREAD

**Issue by Tsuser1** [megoesrawr/Modern-LWC#75]
The current implementation for the command `/lwc menu <basic|advanced>` does not function and appears to be disabled.

**Comment by theyapps** [comment]
It appears that this functionality was present at one point in LWC and was removed. More info is available at https://github.com/Hidendra/LWC/issues/936

Two options for going forward:
1. Reimplement the feature.
2. Remove it from the help text.

I personally support option two as I do not see the benefit of the feature as it is described on the provided link.

**Comment by Tsuser1** [comment]
Removed by latest commit as it no longer exists.

**Issue closed.**
