### ISSUE TITLE
2.0.5 database upgrade still not quite working...

### ISSUE THREAD

**Issue by mrcoffee1026** [megoesrawr/Modern-LWC#78]
Closed my last ticket so I assume you think this issue went away, but it did not.  This basically unregisters 95% of everything in 1.12.2, practically every chest, the majority of doors... signs seem mostly Ok but I stopped checking very far, this doesn't seem to be tested on existing data.

Thanks.

**Comment by theyapps** [comment]
Can you share a database that needs to be updated?

**Comment by mrcoffee1026** [comment]
sure.
[lwc-currentlyonline.zip](https://github.com/megoesrawr/LWCEntityLocking/files/1951822/lwc-currentlyonline.zip)

**Comment by theyapps** [comment]
- Attempted to upgrade the database provided by @mrcoffee1026
- Installed LWC https://github.com/Hidendra/LWC/commit/71811e6fe9256e27787084b54158baa926b65a7a then upgraded to ModernLWC 2.0.6 no protections were lost.

@mrcoffee1026  What version were you upgrading from?

**Comment by mrcoffee1026** [comment]
Everytime I have done this it has removed.... or moved 95% of chest protections... like outside of the world border so that a /lwc admin cleanup just wipes them out.  and version 1.9.4.  This has been going on since your version 2.0.0.

**Comment by theyapps** [comment]
I am actually going in and checking protections and they are remaining protected. Today I loaded 1.9.4 placed an arrangement of single and double chests. Stopped the server and loaded 2.0.7 logged back in and check each chest was still protected.

**Comment by mrcoffee1026** [comment]
Alright then i'll retest on my local with your 2.0.7 and see if that remedies the situation, although every version I've tried recently has obliterated all chest protections so... anyway i'll try this again and let you know.

**Comment by mrcoffee1026** [comment]
This continues to fail in every single test.  Chest protections are all but wiped out.  Practically no protections are being saved at all, I don't know what you're doing for testing, but it isn't thorough.  These are screenshots of just one stack of chests in a single chest room. 
https://imgur.com/a/J82xQdJ

This happens to nearly every chest and sign on the server.

**Comment by mrcoffee1026** [comment]
Also to note, I took a data dump from the database both before and after.  Before, the file.sql is 7.29 MB.  After running the new version of LWC only once, the exported .sql file is 3.62 MB.

**Comment by theyapps** [comment]
Since I cannot use the dump from your database in game I have ran it through the update it is attached. Try importing this database and seeing if protections are in tact. 
[postupdate.sql.tar.gz](https://github.com/megoesrawr/Modern-LWC/files/1958258/postupdate.sql.tar.gz)

**Comment by mrcoffee1026** [comment]
I can't use this on my server though since the file I gave you is quite a bit older than what we're using now.  I did notice - however - that the "blockname" field is empty for every entry in the entire database unless I lock something new, and that is probably where the issue is.  All the old data has an entry for "blockid" which is null for any new entry.  I'll check this and see if it remedies what's on my local copy though since that one has the old file I sent you.

**Comment by mrcoffee1026** [comment]
Same issue with the copy you provided, every chest/sign/everything is unprotected.  Can't help but notice the blockName field is  NULL for every entry even in the data you gave me, but it looks like that's what this value was prior to the change to, so... I'm not sure why that would matter.  But I did notice that locking anything new puts something into that field.

**Comment by mrcoffee1026** [comment]
If you can help we really need a resolution to this soon I'm starting to get a lot of lag-inducing errors from the older copy of LWC these days and since there won't likely be any fix for those other than "get this newer version", I'd really like to not have to tell people all protections have to be remade from scratch.

**Comment by mrcoffee1026** [comment]
Further experimenting I've found that all new entries are being made to the database TWICE.  One row is created with the data field as NULL, and the second with - usually - "rights":[],"flags":[] -- for a chest, for example.  While this is redundant and a waste of resources as far as a database is concerned, it also renders the previous database completely unusable in the new version.  While I was having a time of updating the BlockName field to match the appropriate blockId... which I'd have to give myself to test if it was the correct one, doing so does not prep the database for this new version, the only way to do it would be to include two rows for every one in the database.  PLEASE FIX ASAP.

**Comment by mrcoffee1026** [comment]
this issue sounds sorta like this... except that it's handling all previously locked items - from the older version of LWC - as these two line entries even though they were stored properly back then... and not finding the second line this new version creates it just has them unlocked for everyone.  I would say this applies only to "some" blocks as this issue suggests except that I have yet to find an exception for ANY block where it only needs a single line entered into the database.  Doors and chests should work if nothing else... and they both require both lines in the database to be "locked", wich makes it feel like someone didn't test this very well.

**Comment by mrcoffee1026** [comment]
Issues persist through LATEST JENKINS BUILD #38.  In case you believed changes up to now have magically solved database issues, they have not.  Looks like all chest locks are lost, all sign locks are lost... oddly in double door situations, one of two doors will be preserved (the other lost).  All lock data IS in the database, but since the new version of LWC written handles this data improperly, the effect is that the items have all been unlocked.

**Comment by mrcoffee1026** [comment]
Well that's terrific.  Your last update was for 1.13 ONLY so these issues are STILL unresolved even in 1.13, meaning your new builds work for NEITHER 1.12.2 NOR 1.13.  Well done.  Let me know when you've un-killed this project.
