### ISSUE TITLE
2.0.5 invisible chests

### ISSUE THREAD

**Issue by Sikatsu** [megoesrawr/Modern-LWC#80]
Invisible chests bug until you relog.

Steps to reproduce:

1. Place a double chest
2. Remove the last chest you placed
3. Open the leftover chest
4. Remove the leftover chest

When you want to walk over the location where the chest was placed, you glitch.
Once you relog, it seems theres still a chest on that place you didn't see before.

Which means, the leftover chest did not actually get removed nor unregistered.
When I removed the leftover chest, it also didn't say it got unregistered, but instead said it was protected by me.

**Comment by Sikatsu** [comment]
Well, yes. But none which should conflict. Besides, this never happened
before on older versions.

Op do 26 apr. 2018 02:23 schreef Ryan <notifications@github.com>:

**Comment by theyapps** [comment]
Then as of now, without more information, I am unable to replicate this issue.

**Comment by Sikatsu** [comment]
I'd be more then glad to give you the information you need.

Op vr 27 apr. 2018 21:48 schreef Ryan <notifications@github.com>:

**Comment by theyapps** [comment]
All I can think of now is something with other plugins conflicting in some way or a particular config. So the data that I would offer would be the *.yml files (careful to remove any sql passwords) and list of plugins.

**Comment by Sikatsu** [comment]
I will provide them tomorrow, thanks.

Op vr 27 apr. 2018 21:57 schreef Ryan <notifications@github.com>:

**Comment by theyapps** [comment]
No problem thanks.

**Comment by Sikatsu** [comment]
Just tested on 2.0.7 to make sure the issue still persists, and I can confirm it does.
If it's needed, you can test the issue on my server to see it.

Config files: https://www.dropbox.com/s/f8wpn4c3smrdi2b/LWC.rar?dl=0
Plugins:

PlaceholderAPI, PlugMan, NametagEdit, SuperTrailsPro, FlashLight, CoreProtect, LuckPerms, dynmap, ArmorStandEditor, WorldBorder, Votifier, BannerBoard, ProtocolLib, DeathMessagesPrime, AdvancedPortals, VotingPlugin, FastAsyncWorldEdit, React, mcMMO, Vault, PerWorldInventory, LWC, ZHorse, AAC, AuctionHouse, MyCommand, WorldEdit, Essentials, HeadDatabase, LiteBans, Citizens, CustomGUI, ConditionalCommands, EnjinMinecraftPlugin, PlotSquared, WorldGuard, EssentialsGeoIP, CommandNPC, EssentialsSpawn, RandomCoords, PremiumVanish, Dynmap-WorldGuard, SilkSpawners, Multiverse-Core, Warpalicious, BlockParticles, HolographicDisplays, TitleManager, MyPet, MobHunting, ChatControl, CrateReloaded

**Comment by Tsuser1** [comment]
Unconfirmed, likely caused by another plugin. Try without other plugins installed.

**Issue closed.**
