### ISSUE TITLE
2.0.5 armorstand errors

### ISSUE THREAD

**Issue by Sikatsu** [megoesrawr/Modern-LWC#82]
Error: https://pastebin.com/z13jHjh8

**Comment by Tsuser1** [comment]
Duplicate of #81.

**Comment by Sikatsu** [comment]
This issue was not fixed.
Error: https://pastebin.com/SesZDBD3

**Comment by theyapps** [comment]
And what do you do to trigger this exception?

**Comment by theyapps** [comment]
I have confirmed that now locking armor stands does not seem to function. When I marked it complete this was working. I will look into this now.

**Comment by Sikatsu** [comment]
I trigger the error using flint from the armorstand editor plugin, I can't
edit armorstands without operator otherwise this error occurs. Did not
happen on 2.0.0

Op za 28 apr. 2018 20:16 schreef Ryan Boykin <notifications@github.com>:

**Comment by theyapps** [comment]
@Sikatsu  After I finish fixing this other related issue then I will install armor stand editor and see if I can trigger this exception.

**Comment by Tsuser1** [comment]
Caused by another plugin, related to buggy unsupported entity protections.

**Issue closed.**
