### ISSUE TITLE
LWC Killing Server TPS

### ISSUE THREAD

**Issue by InfinityAspire** [megoesrawr/Modern-LWC#86]
Went from version 1.9.4 of LWC to 2.0.5
This is the timing results after 1 hour and 5 players
[Timings](https://prnt.sc/j9xj4p)
TPS down from 20 to 9

**Comment by megoesrawr** [comment]
I need a link to the timings not a screenshot.

**Comment by Tsuser1** [comment]
Fixed in latest development builds.

**Issue closed.**
