### ISSUE TITLE
Lockpicking suggestion

### ISSUE THREAD

**Issue by Ezzcargot** [megoesrawr/Modern-LWC#93]
**Short five word summary of issue:** 
This is a suggestion for adding a lockpick feature.
**Detailed description of problem:**

Hello, I have a suggestion for the plugin ModernLWC: to add a lockpick:
It's a simple object, but when you right-click on a purchased door, there is a percentage chance that it opens (configurable), and another percentage chance for the player and the item to take damage. This idea comes from the Lockpick-n-rent plugin, but it was dropped and is no longer valid for 1.12. This would be a great idea since I think this function would fit perfectly in the plugin. There could be several items, we could configure the item, and the percentages of luck and the damage taken by the item and the player.

Thank you very much 😄 
Nathan

<paste it here between the little tick marks>
```

**Comment by Tsuser1** [comment]
Thank you for the suggestion, we will review your idea and get back to you soon. We are currently making a stable version of the database update that should dramatically increase performance when using the MySQL database engine. If you have any other suggestions like this, please feel free to open another ticket.

**Comment by Kowaman** [comment]
@Ezzcargot Hi, I coded something like this for my server, message me on Discord if you'd like to see it. Llir#5410

**Comment by Tsuser1** [comment]
We have decided this will unfortunately not be integrated into Modern LWC as it does not truly fit the purpose of the plugin. Feel free to develop an addon for LWC that adds this functionality.

**Issue closed.**
