### ISSUE TITLE
Storage issue + global limit issue

### ISSUE THREAD

**Issue by JohOply** [megoesrawr/Modern-LWC#97]
**LWC Version (/lwc admin version):** 2.0.7
**Server version (/version):** git-Spigot-4bd94dc-fb414fe (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Short five word summary of issue:** 

Storage issue (SQLite & Mysql)
- default limit don't working as global limit
- some blocks are protected twice in database

**Detailed description of problem:**

I tried to create limits per groups, but they don't seem work as excpeted: i can protect beyond the limit, like here : https://i.imgur.com/mWgxiwh.png

It is wreid because I cannot protect more jungle doors for instance, so i find my protections and some blocks are sometimes protected twice : https://pastebin.com/1QJVAbev (also, iron door was unprotected but still appear in database https://i.imgur.com/BrfEdJV.png )

I tried both Sqlite and Mysql, it was the same result
I tried to use lwc admin cleanup, but nothing was removed.

So I think there is two bugs:

- default limit don't working as global limit
- some blocks are protected twice in database

My config:

- Core: https://pastebin.com/U5mh0qNY
- Limits: https://pastebin.com/5eRdXKYr

No error in console, only messages like:
```
[14:14:36 INFO]: [LWC] onBlockInteract com.griefcraft.scripting.event.LWCBlockInteractEvent@46af9659
[14:14:37 INFO]: [LWC] onBlockInteract com.griefcraft.scripting.event.LWCBlockInteractEvent@5bef4ed8
[14:14:38 INFO]: [LWC] onBlockInteract com.griefcraft.scripting.event.LWCBlockInteractEvent@4df42007
```

Thanks for reading

**Comment by megoesrawr** [comment]
"some blocks are protected twice in database" is a repeat of #78 and the limit feature works like this. The default limit is for ALL blocks not defined and ALL blocks already locked. I will look see what I can do to fix the limit thing but idk... As for the repeat issue, We are working on a solution for it ASAP, but I think we all are busy with work/other things.

Global Limit Current Status: **_Gets all the blocks undefined and already locked but doesn't stop defined ones from locking when the limit is reached._**

**Comment by Tsuser1** [comment]
Works as intended.

**Issue closed.**

**Comment by JohOply** [comment]
What about database bugs?

**Comment by pop4959** [comment]
@JohOply Unconfirmed. Database seems to be working correctly on the current builds we are working on. Make a new issue on Tsuser1's repository if the issue persists, and please give more details. Ideally, you can provide a way to reproduce the issue.

**Comment by JohOply** [comment]
Noted, thank you for your answer. I hope database will work correctly in new builds
